[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = false

fs_permissions = [
    { access = "read-write", path = "./output" },
    { access = "read", path = "./broadcast" }
]

[rpc_endpoints]
optimism = "https://mainnet.optimism.io"
opchaina = "http://127.0.0.1:9545"
opchainb = "http://127.0.0.1:9546"

[etherscan]
optimism = { key = "${API_KEY_ETHERSCAN}" }